### ISSUE TITLE
Unable to run spring-security-oauth

### ISSUE THREAD

**Issue by sridharrao** [eugenp/spring-security-oauth#1]
Hi,

I am new to spring-boot, please answer my below question. Million thanks in advance..

In the Read-me file I see below details:

Make sure to run the project on port 8081
Run 4 sub-modules simultaneously
spring-security-oauth-server
spring-security-oauth-resource
spring-security-oauth-ui-implicit
spring-security-oauth-ui-password

But, how do I run all the above modules simultaneously. If I run individual module, only the first oauth-server would run, then it starts complaing about port already been used. So, I am confused how to run all the modules at one shot. Your help is appreciated.

**Comment by sridharrao** [comment]
I was able to do it by configuring with different ports. Thanks, and hence closing ticket.

**Comment by eugenp** [comment]
Sounds good - glad it worked out. Cheers, 
Eugen.
