### ISSUE TITLE
Way to configure HTTPS instead of HTTP

### ISSUE THREAD

**Issue by sridharrao** [eugenp/spring-security-oauth#2]
It would be great if I can know the steps to configure the project to support https instead of http. May be this is not an issue, but i need some help.

Thanks.
-Sridhar

**Comment by eugenp** [comment]
Hey Sridhar - to answer the question here - yes, definitely, you should always run the interaction with the Authorization Server (at least) over HTTPS and never over plain HTTP in a production scenario. 
That being said, that's entirely outside the scope of the tutorial here - and there are plenty of good writeups teaching you how to set up a certificate with your web server. 
Hope that makes sense. Cheers, 
Eugen.
